PROJECT_NAME = ledstrip

CFLAGS += -I$(abspath ../../..) -DHOMEKIT_SHORT_APPLE_UUIDS -DHOMEKIT_MAX_CLIENTS=8

EXTRA_COMPONENT_DIRS += $(abspath ../../../components)

include $(IDF_PATH)/make/project.mk
